image: python:3.7-alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"

before_script:
  - apk add --no-cache --update git build-base libffi-dev libxslt-dev
  - pip install poetry tox

test:
  script:
    - poetry run tox
  artifacts:
    paths:
      - docs/_build

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .pip
    - .tox
