language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true

env:
  global:
    - secure: "q3L244wkl7nF+TK6no4UWoaVILAdp70sDKgSjwnBiibc2vVr0yrhDseitV1kIq4kpfnb+fOHtV32eHOoP77CRkgMjZ1Kh2zVUweavmI4gji1fqz5gJMUlaellAtn+PARgmizAplk0/dMJQ7L/NhwyDnwUFgR10x8b8OZqlkBGQpf6YDefGs9d8VA1J8Fni7YsvOpySLQR9LFSn5b7BmgQ1aysjJVn/VEKpfGld9qEsNzGi1TZ7P0AETVyjHZ4KOfx9m0YiARMAlobDDEIlYm940PCo1n+GPxUFkP5pa95r92LHe9/gZvgD1UKLkAaousR2GLsqIn//ccaj4h2oat+4lM59CkJRXI4E+iY/Q3Df/nZINbFxr/7HPKxa/9cUXnKOODm12b9S5XDul1rwlGAH4xUA2a+sLPXhaGOPKh+nim00iVpxiHsb/nIMyakrWtWLyMK2RPQi7k3o9iUReSs2gYPz6VBdjsnJAD/k3ZFfRHfjNFKzBSGuCduK+u9kSPz6wQBNLlBCw9xSQ5SUbKAzPnhq91NhklEvV6sYfJBibS7mHgTvoaw+JbxqQlmQyQPUkVKHB3pcAzvl8M3hAxHGL5s65JyJGfSoSiSAjn0ATp7kZVGf292LOoUVRuLyK2zkUqjJUdHyTFNcny818aFloasZbsjfesgSbovAJOlfc="

install:
  - pip install poetry tox

script:
  - poetry run tox

deploy:
  - provider: script
    script: poetry publish --username Ovv --password $PYPI_PASS --build
    on:
      repo: Eyepea/pillars
      branch: master
      python: '3.7'
      tags: true
