language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true

install:
  - pip install poetry tox

script:
  - poetry run tox

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: Ovv
    password:
      secure: bA+YZtpGWYgxuWSxqqjeaHVRYL60jUWeJawMhtACQxFc21Xre9/3wtbdRcd55ZQqe0k0Q1YnJ+V5LIa2npsmTOaJMN6ZOJy7qFqt6fCQzb47SYEw3oXZZdNPFtcu5kMqdwU41EB131Cs/igfZYsTVRSPD/Qzj23Dydlz1ndcHUGf8gRtDbW0ErOW+W7yr9RR1ZfoXYFRNzi7YsnGB32qj2Iq02g/CzOH/8sTPV0sReS1EleHj9EGxdLje6WcSIAMEquDXReANsVon48Xm+DK3F4+x2sDnlRta4+dt6XDeDxoGlMMQ/CAy5yTcIzcDrY/RkpxujzY3LbANVHoINrPTMbqO6VnUJTABMNGquGKb1pcH3FQ3mOjZ9IxEGgcUA/VH+Ml2zWG0Y6aHSfJsLTPunxlAEs8j6A6en/xfqPBpBtIpBKUaBik7xzmxvP9U5Ikww5ud3nMliKwO1HasFOgyhaf2Ey3cvwyvaM8Lvu18mKQJJ876mrVZ7AISLHRuQIZ11HfihA5UKY9kVuKd6boJ03HbKrTtXt/4+YPtUYiE48GZMM9ur4odg5CajMZbG1ApBT9cemKDVkPKO0Xi21VtIQ8/ws5vKuupD6O5JPkCveMbj6TUVZGJ92cNyXGQoQq4cQ52qchuvNBmiZoX2V2TZIj46i5o5S9DW4y/wheXtg=
    on:
      repo: Eyepea/pillars
      branch: master
      python: '3.7'
      tags: true
